package com.lemillion.minke.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006d3a)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF73fca8)
val md_theme_light_onPrimaryContainer = Color(0xFF00210d)
val md_theme_light_secondary = Color(0xFF4f6353)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd2e8d4)
val md_theme_light_onSecondaryContainer = Color(0xFF0d1f13)
val md_theme_light_tertiary = Color(0xFF934c00)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdcc2)
val md_theme_light_onTertiaryContainer = Color(0xFF301400)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcf6)
val md_theme_light_onBackground = Color(0xFF1a1c19)
val md_theme_light_surface = Color(0xFFfcfcf6)
val md_theme_light_onSurface = Color(0xFF1a1c19)
val md_theme_light_surfaceVariant = Color(0xFFdce5db)
val md_theme_light_onSurfaceVariant = Color(0xFF414942)
val md_theme_light_outline = Color(0xFF717971)
val md_theme_light_inverseOnSurface = Color(0xFFf1f1eb)
val md_theme_light_inverseSurface = Color(0xFF2f312d)

val md_theme_dark_primary = Color(0xFF54df8f)
val md_theme_dark_onPrimary = Color(0xFF00391b)
val md_theme_dark_primaryContainer = Color(0xFF00522a)
val md_theme_dark_onPrimaryContainer = Color(0xFF73fca8)
val md_theme_dark_secondary = Color(0xFFb6ccb9)
val md_theme_dark_onSecondary = Color(0xFF223427)
val md_theme_dark_secondaryContainer = Color(0xFF374b3c)
val md_theme_dark_onSecondaryContainer = Color(0xFFd2e8d4)
val md_theme_dark_tertiary = Color(0xFFffb77d)
val md_theme_dark_onTertiary = Color(0xFF4e2500)
val md_theme_dark_tertiaryContainer = Color(0xFF703800)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdcc2)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c19)
val md_theme_dark_onBackground = Color(0xFFe2e3dc)
val md_theme_dark_surface = Color(0xFF1a1c19)
val md_theme_dark_onSurface = Color(0xFFe2e3dc)
val md_theme_dark_surfaceVariant = Color(0xFF414942)
val md_theme_dark_onSurfaceVariant = Color(0xFFc0c9bf)
val md_theme_dark_outline = Color(0xFF8a938a)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c19)
val md_theme_dark_inverseSurface = Color(0xFFe2e3dc)

val seed = Color(0xFF37c87a)
val error = Color(0xFFba1b1b)